image:
  - Visual Studio 2017
platform: x64

install:
  - set PATH=%PATH%;C:\Python37-x64\Scripts
  - pip.exe install conan
  - conan user
  - conan remote add public-conan https://api.bintray.com/conan/bincrafters/public-conan
  - conan remote add theirix https://api.bintray.com/conan/bincrafters/theirix
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - git submodule update --init --recursive

build_script:
  - mkdir build
  - conan install . -if="build"
  - cd build
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmake .. -G "Visual Studio 15 2017 Win64"
  - cmake --build . --config Release
