kind: pipeline
type: docker
name: debian

platform:
  arch: amd64
  os: linux

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule init
      - git submodule update --recursive --remote

  - name: build
    image: debian:buster
    commands:
      - apt-get update -yq
      - apt-get install -yq build-essential pkg-config cmake libmsgpack-dev
        libboost-dev libboost-system-dev libwebsocketpp-dev zlib1g-dev
        libcurl4-openssl-dev libssl-dev libjsoncpp-dev libwxgtk3.0-dev
      - mkdir build && cd build
      - cmake ..
      - make -j$(nproc)

